outputFile: /home/yaroslav/working_folder/private/SUNSHARD/sun-go/output.nomad

job_name: test111
datacenters: DC222
job_type: "1231111"

constraint:
  constraintAttribute: value111
  constraintValue: value111

update:
  max_parallel = 1
  min_healthy_time = "10s"
  healthy_deadline = "3m"
  progress_deadline = "10m"
  auto_revert = false
  canary = 0

group:
  name: nginx
  count
  network_mode: "123qq1111"
  network:
    - name: nexus_web
      to: 8081111111
      static: 808111
    - name: nexus
      to: 500011
    - name: nexus_static
  scaling
  service:
    - name: "nginx"
      port: "http"
      tags: ["nginx"]
  task:
    name:
    template: 
      - name: load-balancer.conf
        destination   = "local/load-balancer.conf"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      - 

