job:
  name: "grafana"
  datacenters: ["SUNSHARD"]
  type: "service" # chart type
	namespace: "monitoring"

  meta:
    run_uuid: "${uuidv4()}" # chart deploy_version

  group:
   - name: "grafana"
      count: 1

      volume:
        name: "grafana"
        type: "csi"
        source: "grafana"
        read_only: false
        attachment_mode: "file-system"
        access_mode: "multi-node-multi-writer"

      network:
        - name: "grafana_ui"

      task:
        name: "grafana"
        driver: "docker"

        config:
          image: "grafana/grafana:9.3.1"
          force_pull: true
          ports: ["grafana_ui"]

          volumes: 
            - "local/datasources:/etc/grafana/provisioning/datasources"
            - "local/dashboards:/etc/grafana/provisioning/dashboards"

        ## ТУТ НАДО ПОДУМАТЬ КАК ЛУЧШЕ 
        ## В ОРИГИНАЛЕ ПОСМОТРЕТЬ СТРОКУ 34-42
        volume_mount:
          - volume: grafana
            destination: "/var/lib/grafana"
          - volume: grafana
            destination: "/var/lib/grafana/dashboards"

        template:
          - name: prometheus.yaml
            destination: "local/datasources/prometheus.yaml"
            change_mode: "signal"
            change_signal: "SIGHUP"
          - name: loki.yaml
            destination: "local/datasources/loki.yaml"
          - name: nomad-autoscaler.yaml
            destination: "local/dashboards/nomad-autoscaler.yaml"

        env:
          - GF_SECURITY_ADMIN_USER: "admin"
          - GF_SECURITY_ADMIN_PASSWORD: "Lqrs15d7"
          - GF_SERVER_HTTP_PORT: "${NOMAD_PORT_grafana_ui}"
          - GF_INSTALL_PLUGINS: "natel-discrete-panel"

        service:
          - name: "grafana"
            provider: consul (default = consul)
            port: "grafana_ui"
            tags: ["nginx", "test"]
            check:
              type: "http"
              path: "/api/health"
              interval: "10s"
              timeout: "2s"

        resources:
          cpu: 1000
          memory: 1000