job:
  name: "nginx"
  datacenters: ["dc1"]
  type: "смотреть prism.yaml"
  namespace: "default"
  meta:
    run_uuid: "${uuidv4()}"

  group:
    - name: "nginx"
      count: 1
      network_mode: "bridge"
      network:
        - name: "http"
          static: 80
          to: 80
        - name: "https"
          to: 443
        - name: "test"
          static: 81
        - name: "test1"

      scaling:
        enabled: true
        min: 1
        max: 6

      service:
        - name: "nginx"
          provider: consul
          port: "http"
          tags: ["nginx", "test"]
          check:
            name: "alive"
            type: "http"
            path: "/"
            interval: "10s"
            timeout: "2s"
          connect:
            sidecar_service: true
        - name: "nginx-https"
          provider: consul (default = consul)
          port: "https"
          tags: ["nginx", "test"]
          connect:
            sidecar_service:
              proxy:
                upstreams:
                  destination_name: "nginx"
                  local_bind_port: 80

      restart:
        attempts: 10
        interval: "5m"
        delay: "25s"
        mode: "delay"

      task:
        name: "nginx"
        driver: "docker"
        config:
          image: "nginx"
          force_pull: true
          ports: ["http"]
          volumes:
            - "local:/etc/nginx/conf.d"
            - "local/test.conf:/etc/nginx/conf.d/test.conf"
            - "custom_path:/custom_path_in_container"

          template:
            - name: load-balancer.conf
              destination: "local/load-balancer.conf"
              change_mode: "signal"
              change_signal: "SIGHUP"
          env:
            - WORDPRESS_DB_HOST = "${NOMAD_UPSTREAM_IP_mysql-server}"
            - WORDPRESS_CONFIG_EXTRA = "define('WP_HOME','wp.sunshard.ru:443')"
            - WORDPRESS_CONFIG_EXTRA = "define('WP_ALLOW_REPAIR', true );\ndefine('WP_HOME','https://wp.sunshard.space');\ndefine('WP_SITEURL','https://wp.sunshard.space');"

        resources:
          cpu: 1000
          memory: 1000
