# The name of the Prism Pack.
name: "PRISM_PACK_NAME"

# Description of the Prism Pack.
description: "A prism pack for Nomad"

# Information about those who maintain the Prism Pack.
maintainers:
  - "Name, email, etc."

# Specifies the Nomad scheduler to use.
# Nomad provides the service, system, batch, and sysbatch schedulers.
type: "service"

# Links to source code or resources associated with the Prism Pack.
# sources:
#   - https://some-repo.com/path/

# The version of the application it contains.
deploy_version: "0.0.1"

# The version of the Prism Pack,
# aiding in tracking changes and updates to the Prism Pack.
pack_version: "0.0.1"

# The version of Nomad on which the Prism Pack has been tested.
nomad_version: "1.7.2"

# Specifies dependencies of the current Prism Pack on other Prism Packs,
# which will be automatically installed when installing the main Prism Pack.
# dependencies:
#   - name: "dependency-name"
#     pack_version: "0.0.1"
#     path: "/path/to/pack"
#     files:
#       - "dependency_overrides.yaml"
#       - "/path/to/pack/dependency_overrides.yaml"
