name: "test"
description: "A Helm chart for Kubernetes"
type: "service"

deploy_version: "0.0.1"
prism_version: "0.0.1"

dependencies:
  - name: "rabbit"
    prism_version: "1.0"
    path: "project/charts/rabbit"
    config_path: "project/env/prod/config/rabbit_config.yaml"
