name: "test"
description: "A Helm chart for Kubernetes"
type: "service"

dependencies:
  - name: rabbit
    prism_version: "1.0"
    path: "project/charts/rabbit"
    config_path: "project/env/prod/config/rabbit_confog.yaml"

deploy_version: "0.1.0"

prism_version: "1.16.0"