job:
  name: "rabbit"
  datacenters: ["SUNSHARD"]
  type: "service" # chart type
	namespace: "default"

  meta:
    run_uuid: "${uuidv4()}" # chart deploy_version
  
  group:
    - name: "rabbitmq"
      count: 1
      network_mode: "bridge" # network config block - mode = "bridge")

      network:
        - port:
            name: "rabbitmq_amqp"
            static: 5672
            to: 5672
        - port:
            name: "rabbit_ui"
            to: 15672

      task:
        name: "rabbit" 
        driver: "docker"

        config:
          image: "rabbitmq:3-management"
          force_pull: true

        env:
          RABBITMQ_DEFAULT_USER: "test"
          RABBITMQ_DEFAULT_PASS: "test"

        service:
          - name: "rabbit-ui"
            provider: consul (default = consul)
            port: "rabbit_ui"
          - name: "rabbitmq-amqp"
            provider: consul (default = consul)
            port: "rabbitmq_amqp"

        resources:
          cpu: 1000
          memory: 1000
