job:
  name: "nextcloud"
  datacenters: ["SUNSHARD"]
  type: "service" # chart type
  namespace: "default"

  meta:
    run_uuid: "${uuidv4()}" # chart deploy_version

  group:
    - name: "mariadb"
      count: 1
      network_mode: "bridge" # network config block - mode = "bridge")

      update:
        min_healthy_time: "10s"
        healthy_deadline: "5m"
        progress_deadline: "10m"
        auto_revert: true

      scaling:
        enabled: true #(default = false)
        min: 1
        max: 6

      service:
        - name: "mariadb-nextcloud"
          provider: consul (default = consul)
          port: "3306"
          tags: ["database"]
          # Если открываем сервис для консул коннекта
          connect:
            sidecar_service: true

      restart:
        attempts: 2
        interval: "30m"
        delay: "15s"
        mode: "delay"

      task:
        name: "mariadb"
        driver: "docker"

        config:
          image: "mariadb:10.6.4-focal"
          force_pull: true

          env:
            - MYSQL_ROOT_PASSWORD: "test"
            - MYSQL_DATABASE: "nextcloud"
            - MYSQL_USER: "nextcloud"
            - MYSQL_PASSWORD: "lqrs15d7"

        resources:
          cpu: 1000
          memory: 1000

    - name: "nextcloud"
      count: 1
      network_mode: "bridge"

      network:
        - port:
            name: "http"
            to: 80

      update:
        min_healthy_time: "10s"
        healthy_deadline: "5m"
        progress_deadline: "10m"
        auto_revert: true

      service:
        - name: "nextcloud"
          provider: consul (default = consul)
          port: "http"
          tags: ["app"]
          connect:
            sidecar_service:
              proxy:
                upstreams:
                  destination_name: "mariadb-nextcloud"
                  local_bind_port: 3306

      restart:
        attempts: 2
        interval: "30m"
        delay: "15s"
        mode: "fail"

      task:
        name: "nextcloud"
        driver: "docker"

        config:
          image: "nextcloud"

          env:
            - MYSQL_HOST: "${NOMAD_UPSTREAM_ADDR_mariadb-nextcloud}"
            - MYSQL_PASSWORD: "test"
            - MYSQL_DATABASE: "nextcloud"
            - MYSQL_USER: "nextcloud"
            - NEXTCLOUD_TRUSTED_DOMAINS: "next.site.ru"

        resources:
          cpu: 1000
          memory: 1000
